#!/usr/bin/env  bash

set -e

ZNC_USER=$1
ZNC_PASS=$2
CAMPFIRE_PASS=$3
BITLBEE_PASS=$4

ZNC_ROOT="/znc/state"
CONFIG_FILE=${ZNC_ROOT}/configs/znc.conf

if [ ! -d ${ZNC_ROOT}/configs ]; then
    mkdir -p ${ZNC_ROOT}/configs
fi;

if [ ! -e $CONFIG_FILE ]; then

if [ $# -lt 4 ]; then
    echo "Usage: $0 <USER> <PASSWORD> <CAMPFIRE> <BITLBEE>"
    exit 1
fi;

ZNC_SALT="$(dd if=/dev/urandom bs=16c count=1 | md5sum | awk '{print $1}')"
ZNC_HASH="$(echo -n ${ZNC_PASS}${ZNC_SALT} | sha256sum | awk '{print $1}')"

cat<<EOF > ${CONFIG_FILE}
AnonIPLimit = 10
ConnectDelay = 5
LoadModule = palaver
MaxBufferSize = 500
ProtectWebSessions = true
SSLCertFile = ${ZNC_ROOT}/znc.pem
ServerThrottle = 30
Version = 1.0

<Listener listener0>
  AllowIRC = true
  AllowWeb = true
  IPv4 = true
  IPv6 = true
  Port = 6668
  SSL = true
</Listener>

<User $ZNC_USER>
  Admin = true
  AltNick = ${ZNC_USER}_
  AppendTimestamp = false
  AutoClearChanBuffer = true
  Buffer = 50
  ChanModes = +stn
  DenyLoadMod = false
  DenySetBindHost = false
  Ident = $ZNC_USER
  JoinTries = 10
  LoadModule = controlpanel
  LoadModule = chansaver
  LoadModule = clientaway
  LoadModule = perform
  MaxNetworks = 1
  MultiClients = true
  Nick = $ZNC_USER
  PrependTimestamp = true
  QuitMsg = Goodbye
  StatusPrefix = *

  <Network freenode>
    FloodBurst = 4
    FloodRate = 1.00
    IRCConnectEnabled = true
    LoadModule = nickserv
    Server = wright.freenode.net +7070
    Server = hubbard.freenode.net +7070
    Server = card.freenode.net +7070
    Server = verne.freenode.net +7070
  </Network>

  <Network campfire>
    FloodBurst = 4
    FloodRate = 1.00
    IRCConnectEnabled = true
    Server = localhost 7778 ${CAMPFIRE_PASS}
  </Network>

  <Network bitlbee>
    FloodBurst = 4
    FloodRate = 1.00
    IRCConnectEnabled = true
    LoadModule = simple_away
    Server = localhost 6667 ${BITLBEE_PASS}

    <Chan &bitlbee>
    </Chan>
  </Network>

  <Pass password>
    Hash = $ZNC_HASH
    Method = SHA256
    Salt = $ZNC_SALT
  </Pass>
</User>
EOF

fi;

sed -i 's/Server = .* 7778/Server = '$CAMPER_VAN_PORT_7778_TCP_ADDR' 7778/' $CONFIG_FILE
sed -i 's/Server = .* 6667/Server = '$BITLBEE_PORT_6667_TCP_ADDR' 6667/' $CONFIG_FILE

exec znc -r -f -d /znc/state
